// This file is autogenerated by Quiche.
// Do not modify this file directly. Modify .q files in src/ instead.
#![allow(dead_code, unused_variables, unused_mut, unused_imports, unused_parens)]

// Re-export quiche runtime as crate::quiche for generated code
pub mod quiche {
    pub use quiche_runtime::*;
}

use quiche_runtime::*;

// Re-export everything from the transpiled module
include!(concat!(env!("OUT_DIR"), "/lib.rs"));
